[platformio]
build_dir = C:/pio_build/3nhan

[env:esp32-s3-devkitc-1]
platform = platformio/espressif32@6.13.0
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
upload_speed = 460800

board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 8MB
board_build.partitions = huge_app.csv

build_flags =
    -DBOARD_HAS_PSRAM
    -DCORE_DEBUG_LEVEL=1

lib_deps =
    tanakamasayuki/TensorFlowLite_ESP32@1.0.0

lib_ldf_mode = deep+
lib_archive = no